const ASSETS = [
  // Hero
  { src: '/picture/hero.jpg', type: 'image' },

  // Prologue
  { src: '/picture/prologue/云彩.png', type: 'image' },
  { src: '/picture/prologue/横截面.png', type: 'image' },
  { src: '/picture/prologue/Gemini_Generated_285窟内景.png', type: 'image' },

  // Chapter 1
  { src: '/picture/chap1/285窟北壁第二铺.png', type: 'image' },
  { src: '/picture/chap1/285窟敦煌阴氏发愿文.png', type: 'image' },
  { src: '/picture/chap1/285窟北壁第二铺供养人 .png', type: 'image' },
  { src: '/picture/chap1/敦煌日历2022年，第431窟 供养菩萨.png', type: 'image' },
  { src: '/picture/chap1/第285窟北壁第一铺 女贵族供养人.png', type: 'image' },
  { src: '/picture/chap1/礼佛图左.png', type: 'image' },
  { src: '/picture/chap1/礼佛图中.png', type: 'image' },
  { src: '/picture/chap1/礼佛图右.png', type: 'image' },
  { src: '/picture/chap1/礼佛图复原题记.png', type: 'image' },
  { src: '/picture/chap1/段文杰复原临摹莫高窟 130窟 都督夫人礼佛图.png', type: 'image' },
  { src: '/picture/chap1/第98窟 于阗国王李圣天供养像.png', type: 'image' },
  { src: '/picture/chap1/第98窟 五代女供养人欧阳琳1992年复原画.png', type: 'image' },
  { src: '/picture/chap1/第62窟东壁下部 平民供养人及牛车.png', type: 'image' },
  { src: '/picture/chap1/第107窟东壁北侧 奴隶供养人.png', type: 'image' },

  // Chapter 2
  { src: '/picture/chap2/单元标题2.png', type: 'image' },
  { src: '/picture/chap2/武威郡夫人.png', type: 'image' },
  { src: '/picture/chap2/威武郡夫人像展品卡片.jpg', type: 'image' },
  { src: '/picture/chap2/61窟外甥小娘子阴氏一心供养 (2).png', type: 'image' },
  { src: '/picture/chap2/外甥小娘子阴氏供养像.jpg', type: 'image' },
  { src: '/picture/chap2/61窟外甥小娘子阴氏一心供养.png', type: 'image' },
  { src: '/picture/chap2/延萌延胜展品卡片.jpg', type: 'image' },
  { src: '/picture/chap2/阴子升.png', type: 'image' },
  { src: '/picture/chap2/12、河西督僧统抠图版.png', type: 'image' },
  { src: '/picture/chap2/阴善雄.png', type: 'image' },
  { src: '/picture/chap2/13.P.2482阴善雄墓志铭抠图版.png', type: 'image' },
  { src: '/picture/chap2/史崇姬像.png', type: 'image' },
  { src: '/picture/chap2/阴安归像.png', type: 'image' },
  { src: '/picture/chap2/ai武威郡夫人.png', type: 'image' },
  { src: '/picture/chap2/武威郡夫人.png', type: 'image' },
  { src: '/picture/chap2/ai延萌.png', type: 'image' },
  { src: '/picture/chap2/ai延胜.png', type: 'image' },
  { src: '/picture/chap2/阴家小娘子.png', type: 'image' },
  { src: '/picture/chap2/61窟女供养人.png', type: 'image' },
  { src: '/picture/chap2/阴家小娘子文书.png', type: 'image' },
  { src: '/picture/chap2/张议潮及其儿子女婿（抠图）.PNG', type: 'image' },
  { src: '/picture/chap2/阴氏郡君太夫人（抠图）.PNG', type: 'image' },

  // Chapter 3
  { src: '/picture/chap3/单元标题3.png', type: 'image' },
  { src: '/picture/chap3/图经1.png', type: 'image' },
  { src: '/picture/chap3/图经2.png', type: 'image' },
  { src: '/picture/chap3/图经3.png', type: 'image' },
  { src: '/picture/chap3/名族志1.png', type: 'image' },
  { src: '/picture/chap3/名族志2.png', type: 'image' },
  { src: '/picture/chap3/名族志3.png', type: 'image' },
  { src: '/picture/chap3/河流.gif', type: 'image' },
  { src: '/picture/chap3/宝雨经.jpg', type: 'image' },
  { src: '/picture/chap3/431窟南壁壁画.jpg', type: 'image' },
  { src: '/picture/chap3/431影响1.jpg', type: 'image' },
  { src: '/picture/chap3/431影响2.jpg', type: 'image' },
  { src: '/picture/chap3/217窟影响.jpg', type: 'image' },
  { src: '/picture/chap3/217窟北壁壁画.jpg', type: 'image' },
  { src: '/picture/chap3/217窟东壁壁画.jpg', type: 'image' },
  { src: '/picture/chap3/217窟南壁壁画.jpg', type: 'image' },
  { src: '/picture/chap3/217窟供养人.PNG', type: 'image' },
  { src: '/picture/chap3/231窟供养人壁画2.png', type: 'image' },
  { src: '/picture/chap3/阴氏家族任职图.png', type: 'image' },
  { src: '/picture/chap3/阴处士碑.png', type: 'image' },
  { src: '/picture/chap3/吐蕃告身1.png', type: 'image' },
  { src: '/picture/chap3/吐蕃告身2.png', type: 'image' },
  { src: '/picture/chap3/吐蕃告身3.png', type: 'image' },
  { src: '/picture/chap3/吐蕃告身4.png', type: 'image' },
  { src: '/picture/chap3/吐蕃告身5.png', type: 'image' },
  { src: '/picture/chap3/张议潮统军出行图右往左1.gif', type: 'image' },
  { src: '/picture/chap3/张议潮统军出行图右往左2.gif', type: 'image' },
  { src: '/picture/chap3/张议潮统军出行图右往左3.gif', type: 'image' },
  { src: '/picture/chap3/张议潮统军出行图右往左4.gif', type: 'image' },
  { src: '/picture/chap3/张议潮供养像（抠图）.png', type: 'image' },
  { src: '/picture/chap3/张议潮夫人（抠图）.png', type: 'image' },
  { src: '/picture/chap3/安国寺尼智慧性供养像（抠图）.PNG', type: 'image' },
  // 3D Models
  { src: '/picture/chap3/像塔.glb', type: 'model' },
  { src: '/picture/chap3/白狼建模.glb', type: 'model' },

  // Chapter 4
  { src: '/picture/chap4/单元标题4.png', type: 'image' },
  { src: '/picture/chap4/藏经洞进入页面（2）.png', type: 'image' },
  { src: '/picture/chap4/藏经洞里有什么（1）.png', type: 'image' },
  { src: '/picture/chap4/藏经洞里有什么（2）.png', type: 'image' },
  { src: '/picture/chap4/斯坦因.png', type: 'image' },
  { src: '/picture/chap4/伯希和.png', type: 'image' },
  { src: '/picture/chap4/奥登堡.png', type: 'image' },
  { src: '/picture/chap4/大谷光瑞.png', type: 'image' },
  { src: '/picture/chap4/流失文物（1）存哈佛大学艺术博物馆.png', type: 'image' },
  { src: '/picture/chap4/流失文物（2）哈佛大学博物馆.png', type: 'image' },
  { src: '/picture/chap4/流失文物（3）英国国家博物馆.png', type: 'image' },
  { src: '/picture/chap4/流失文物（4）英国国家博物馆.png', type: 'image' },
  { src: '/picture/chap4/流失文物（5）俄国人奥登堡.png', type: 'image' },
  { src: '/picture/chap4/流失文物（6）俄国人奥登堡.png', type: 'image' },
  { src: '/picture/chap4/流失文物（7）俄国人奥登堡.png', type: 'image' },
  { src: '/picture/chap4/流失文物（8）纳尔.png', type: 'image' },
  { src: '/picture/chap4/流失文物（9）纳尔.png', type: 'image' },
  { src: '/picture/chap4/流失文物（10）纳尔.png', type: 'image' },
  { src: '/picture/chap4/流失文物（11）法国国家图书馆.png', type: 'image' },
]

export default ASSETS
